imports:
    - { resource: config.yml }

service_providers:
    monolog:
        parameters:
            monolog.logfile: %log_path%/application.log
            monolog.name: APPLICATION
            
    service_controller:
        class: Silex\Provider\ServiceControllerServiceProvider
        
    active_record:
        class: Providers\ActiveRecordServiceProvider     
    
    http_cache:
        class: Silex\Provider\HttpCacheServiceProvider
        parameters:
            http_cache.cache_dir: %cache_path%/http
            http_cache.esi: ~

    url_generator:
        class: Silex\Provider\UrlGeneratorServiceProvider

    form:
        class: Silex\Provider\FormServiceProvider
    
    session:
        class: Silex\Provider\SessionServiceProvider
        
    
        

